# fly.toml app configuration file generated for jeff-bridges on 2023-05-26T16:57:23+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jeff-bridges"
primary_region = "ams"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
